name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: |
          npm install -g tree-sitter-cli node-gyp
          npm install

      - name: Test
        run: |
          tree-sitter generate
          tree-sitter test

      - name: Build bindings
        run: |
          node-gyp configure
          node-gyp build

  bindings-rust:
    needs: test
    name: Rust Bindings
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: |
          cargo test
